{{- if .Values.certificates.static -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "sidecar-injector.name" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
  {{- with .Values.webhook.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: kyverno-envoy-sidecar.kyverno-envoy-sidecar-injector.svc
    clientConfig:
      service:
        name: {{ template "sidecar-injector.name" . }}
        namespace: {{ template "kyverno.lib.namespace" . }}
        path: "/mutate"
      caBundle: {{ index .Values.certificates.static.crt | b64enc }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    admissionReviewVersions: [ v1 ]
    rules:
      - apiGroups: [ '' ]
        apiVersions: [ v1 ]
        resources: [ pods ]
        operations: [ CREATE ]
        scope: '*'
    {{- with .Values.webhook.objectSelector }}
    objectSelector:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
{{- end }}
